// Generates src/abi.ts from the Hardhat artifact (artifacts/ is gitignored, so abi.ts is committed).
// Run from sdk/: npm run generate:abi   (requires `npx hardhat compile` at the repo root first)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const artifactPath = fileURLToPath(
  new URL("../../artifacts/contracts/WeatherMarket.sol/WeatherMarket.json", import.meta.url),
);
const outPath = fileURLToPath(new URL("../src/abi.ts", import.meta.url));

const { abi } = JSON.parse(readFileSync(artifactPath, "utf8")) as { abi?: unknown[] };
if (!Array.isArray(abi) || abi.length === 0) {
  throw new Error(`No abi found in ${artifactPath}`);
}

const out =
  "// AUTO-GENERATED by scripts/generate-abi.ts from artifacts/contracts/WeatherMarket.sol/WeatherMarket.json.\n" +
  "// Do not edit by hand; run `npm run generate:abi`.\n" +
  `export const weatherMarketAbi = ${JSON.stringify(abi, null, 2)} as const;\n`;

writeFileSync(outPath, out);
console.log(`Wrote ${abi.length} ABI entries to ${outPath}`);
